[package]
name = "bevy_steganography"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"

[dependencies.bevy]
version = "0.13"

[dependencies.occule]
git = "http://github.com/exvacuum/occule"
